<div class="col-md-12">
    <h3>Zápis Volitelnách předmětů <small>změny jsou průběžně ukládány</small>
        <div class="btn-group pull-right">
            <a href="#" class="btn btn-success">Dokončit zápis</a>
            <a href="<?=$router->pathFor('subjects-student')?>" class="btn btn-default">Zpět</a>
        </div>
    </h3>
    <hr />
</div>
<div class="col-md-12">
    <div class="list-group">
        <div class="list-group-item list-group-item-success" style="display: flow-root">
            <div class="col-md-10">
                <h4 class="list-group-item-heading"><small>Zapsáno jako <b>volitelný předmět</b></small><br /><br />CAE – Certificate in Advanced English</h4>
                <p class="list-group-item-text">
                    Příprava na zkoušky Cambridge zkoušky CAE na úrovni C1. Probírání vzorových testů a
                    rozbor jejich zvládnutí v oblasti čtení, poslechu, gramatiky, eseje a ústní části. Rozšiřování
                    slovní zásoby nutné pro zvládnutí těchto testů. Seminář je určen pro studenty na vyšší úrovni
                    AJ.
                    <br /><br />
                    Spolupráce s jazykovou agenturou Cambridge P.A.R.K. U této agentury se zároveň studenti
                    mohou na začátku roku závazně na zkoušku přihlásit a na jaře 2019 ji absolvovat v budově
                    naší školy. Pro přihlášené je mock test zdarma.
                </p>
            </div>
            <div class="col-md-2">
                <div class="btn-group pull-right">
                    <button type="button" class="btn btn-default">Zrušit</button>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#" class="btn">Zapsat</a></li>
                        <li><a href="#" class="btn">Náhradní předmět</a></li>
                        <li><a href="#" class="btn">Dobrovolný seminář</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#" class="btn disabled">Zrušit zápis</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="list-group-item" style="display: flow-root">
            <h4 class="list-group-item-heading">List group item heading</h4>
            <p class="list-group-item-text">...</p>
        </div>
        <div class="list-group-item" style="display: flow-root">
            <h4 class="list-group-item-heading">List group item heading</h4>
            <p class="list-group-item-text">...</p>
        </div>
    </div>
</div>