<div class="col-md-12">
    <h3>Zápis Volitelnách předmětů <small>změny jsou průběžně ukládány</small>
        <div class="btn-group pull-right">
            <a href="#" class="btn btn-success">Dokončit zápis</a>
            <a href="<?=$router->pathFor('subjects-student')?>" class="btn btn-default">Zpět</a>
        </div>
    </h3>
    <hr />
</div>
<div class="col-md-12">
    <div class="list-group">
        <?php foreach ($subjects as $subject):?>
        <div class="list-group-item <?=
is_numeric($subject['level']) ? [
    'list-group-item-success',
    'list-group-item-info',
    'list-group-item-warning'
    ][$subject['level']] : ''
?>" style="display: flow-root">
            <div class="col-md-10">
                <h4 class="list-group-item-heading " style="margin-bottom: 10px;">
                <?php if (is_numeric($subject['level'])):?>
                    <small>Zapsáno jako <b><?=['volitelný předmět', 'náhradní předmět', 'dobrovolný seminář'][$subject['level']]?></b></small><br /><br />
                <?php endif;?>
                <?=$subject['name']?>
                </h4>
                <p class="list-group-item-text">
                    <?=str_replace('\n', '<br /><br />', $subject['annotation'])?>
                </p>
            </div>
            <div class="col-md-2">
                <div class="btn-group pull-right">
                    <button type="button" class="btn btn-default"><?=is_numeric($subject['level'])?'Zrušit zápis':'Zapsat'?></button>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#" class="btn">Zapsat</a></li>
                        <li><a href="#" class="btn">Náhradní předmět</a></li>
                        <li><a href="#" class="btn">Dobrovolný seminář</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#" class="btn disabled">Zrušit zápis</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <?php endforeach;?>
    </div>
</div>