<div class="panel panel-default">
    <div class="panel-body">
        <p>Seznam zkontrolujte, odešlete a poté vytiskněte.</p>
        <?php if ($state != 0):?>
        <a class="btn btn-default" href="<?=$router->pathFor('subjects-student')?>">Zpět</a>
        <div class="pull-right btn-group">
            <button class="btn btn-success disabled" data-toggle="tooltip" data-placement="top" title="Seznam již byl odeslán">Odeslat</button>
            <button class="btn btn-primary" onclick="document.getElementById('pdf').contentWindow.print()">Tisk</button>
        </div>
        <?php else:?>
        <a class="btn btn-default" href="<?=$router->pathFor('subjects-student-edit', ["id" => $listID])?>">Zpět</a>
        <div class="pull-right">
            <div class="btn-group">
                <button class="btn btn-success" onclick="document.getElementById('send').submit()">Odeslat</button>
                <button class="btn btn-primary disabled" data-toggle="tooltip" data-placement="top" title="Před tiskem seznam odešlete">Tisk</button>
            </div>
        </div>
        <?php endif?>
    </div>
</div>
<h4>Předměty</h4>
<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th class="col-md-1">Kód</th>
            <th class="col-md-6">Předmět</th>
            <th class="col-md-5">Typ zápisu</th>
        </tr>
    </thead>
    <?php foreach($subjects as $subject):?>
    <tr>
        <td><?=$subject['code']?></td>
        <td><?=$subject['name']?></td>
        <td><?=[
            'Volitelný předmět',
            'Náhradní předmět',
            'Dobrovolný seminář'
        ][$subject['level']]?></td>
    </tr>
    <?php endforeach;?>
</table>
</div>

<form method="post" id="send" action="<?=$router->pathFor('subjects-student-preview', ["id" => $listID])?>">
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="_METHOD" value="PUT" />
</form>

<?php if ($state != 0):?>
<iframe id="pdf" src="<?=$router->pathFor('subjects-student-generate', ['id' => $listID])?>" style="display: none;">
</iframe>
<?php endif;?>