<?php require __dir__."/../sidebar/header.phtml"?>

<h1 class="page-header">Seznam zápisů</h1>

<div class="row">
<div class="table-responsive">
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID zápisu</th>
        <th>Jméno</th>
        <th>Třída</th>
        <th>Počet uzavřených předmětů</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1,001</td>
        <td>Pepík Nováků</td>
        <td>4. B</td>
        <td>5</td>
    </tr>
    <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
    </tr>
    </tbody>
</table>
</div>

<?php require __dir__."/sidebar/footer.phtml"?>