<?php require __dir__."/../sidebar/header.phtml"?>

<h1 class="page-header">Úprava zápisu</h1>

<h2 class="sub-header"><?=$user->getName()?></h2>
<div class="table-responsive">
<table class="table table-striped">
    <thead>
    <tr>
        <th>Kód</th>
        <th>Název</th>
        <th>Typ zápisu</th>
        <th>Otevřen?</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($subjects as $subject):?>
    <tr <?=$subject['state'] == 1 ?'class="danger"':''?>>
        <td><?=$subject['code']?></td>
        <td><?=$subject['name']?></td>
        <td><?=$subject['level'] == 0 ? 'Volitelný' : 'Náhradní'?></td>
        <td><?=$subject['state'] == 1 ? 'ne' : 'ano'?></td>
    </tr>
    <?php endforeach;?>
    </tbody>
</table>
</div>

// uložit (pozor zápis neprochází kontrolou)

<?php require __dir__."/../sidebar/footer.phtml"?>
