<div class="col-md-12">
    <h3><?=$lang->g('title', 'teacher-view')?> <small><?=$lang->g('heading', 'teacher-view')?></small>
        <a href="<?=$router->pathFor('subjects-teacher')?>" class="btn btn-default pull-right"><?=$lang->g('back', 'teacher-view')?></a>
    </h3>
    <hr />
</div>
<div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong><?=$lang->g('students', 'teacher-view')?></strong>
        </div>
        <div class="panel-body">
            <?php if (is_array(@$students) && count($students)):?>
                <ul class='list-group'>
                    <?php foreach ($students as $student):?>
                        <li class='list-group-item<?=$student['invalid']?' list-group-item-danger':''?>'><?=$student['user']->getName()?> (<?=$student['user']->getUname()?>) <b><?=$student['user']->getAttribute('class')?></b>
                            <span class='pull-right'><?=$lang->g('list', 'teacher-view')?> <a href="<?=$router->pathFor('subjects-teacher-generate', ['id' => $student['list']])?>" target="_blank"><?=$student['list']?></a></span>
                        </li>
                    <?php endforeach;?>
                </ul>
            <?php else:?>
                <span class='text-muted'><?=$lang->g('notfound', 'teacher-view')?></span>
            <?php endif?>
        </div>
    </div>
</div>
