<div class="col-md-12">
<h3>Seznam studentů <small>a jejich kánonů</small>
    <a href="<?=$router->pathFor('lists')?>" class="btn btn-default pull-right">Zpět</a>
</h3>
<hr />
</div>
<div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Studenti</strong>
        </div>
        <div class="panel-body">
        <?php if (is_array(@$students) && count($students)):?>
            <ul class='list-group'>
            <?php foreach($students as $student):?>
                <li class='list-group-item'><?=$student['user']->getName()?> (<?=$student['user']->getUname()?>) <b><?=$student['user']->getLocalisedClass()?></b> 
                <span class='pull-right'>Kánon: <a href="<?=$router->pathFor('lists-teacher-generate', ['id' => $student['list']])?>" target="_blank"><?=$student['list']?></a></span>
                </li>
            <?php endforeach;?>
            </ul>
        <?php else:?>
            <span class='text-muted'>Žádní studenti</span>
        <?php endif?>
        </div>
    </div>
</div>