<?php require __dir__."/../sidebar/header.phtml"?>

<h1 class="page-header">Seznamy předmětů</h1>

<form method="post" class="form-inline" action="<?=$router->pathFor('subjects-admin-subjects-edit', ['id' => 'new'])?>">
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="_METHOD" value="PUT" />
    <div class="form-group">
        <label for="name" style="margin-right: 5px;">Založit novou verzi</label>
        <input type="text" class="form-control" name="name" id="name" placeholder="Název">
    </div>
    <input type="submit" class="btn btn-default" value="Odeslat">
</form>

<hr />

<form method="post" class="form-inline" action="<?=$router->pathFor('subjects-admin-subjects-dash')?>">
    <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
    <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
    <input type="hidden" name="_METHOD" value="PUT" />
    <div class="form-group">
        <label for="v7" style="margin-right: 5px;">Verze pro 7. ročník</label>
        <select class="form-control" name="v7" required>
            <option disabled selected value="">Zvolte verzi</option>
            <?php foreach ($versions as $version):?>
            <option value="<?=$version['id']?>" <?=@$active_versions[7] == $version['id']?'selected':''?>><?=$version['name']?></option>
            <?php endforeach;?>
        </select>
    </div><br /><br />
    <div class="form-group">
        <label for="v7" style="margin-right: 5px;">Verze pro 8. ročník</label>
        <select class="form-control" name="v8" required>
            <option disabled selected value="">Zvolte verzi</option>
            <?php foreach ($versions as $version):?>
            <option value="<?=$version['id']?>" <?=@$active_versions[8] == $version['id']?'selected':''?>><?=$version['name']?></option>
            <?php endforeach;?>
        </select>
    </div><br />
    <input type="submit" class="btn btn-default" value="Odeslat">
</form>

<hr />

<h2 class="sub-header">Seznamy verzí</h2>
<?php if (is_array(@$versions) && count($versions)):?>
<div class="table-responsive">
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID seznamu</th>
        <th>Název</th>
        <th>Počet předmětů</th>
        <th>Limity</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($versions as $entry):?>
    <tr>
        <td><a href="<?=$router->pathFor('subjects-admin-subjects-edit', ['id' => $entry['id']])?>"><?=$entry['id']?></a></td>
        <td><?=$entry['name']?></td>
        <td><?=$entry['count']?></td>
        <td><?=$entry['limit']?>/<?=$entry['limit_spare']?></td>
    </tr>
    <?php endforeach;?>
    </tbody>
</table>
</div>
<?php else:?>
Žádné seznamy nenalezeny
<?php endif;?>

<?php require __dir__."/../sidebar/footer.phtml"?>