<?php require __dir__."/sidebar/header.phtml"?>

<h1 class="page-header">Dashboard</h1>
<!--div class="row">
<div class="col-xs-6 col-sm-3 col-sm-offset-1 col-md-offset-2 placeholder">
    <div id="piechart1" style="width: 200px; height: 200px;"></div>
    <h4>Stav zápisů</h4>
    <span class="text-muted">Jednotlivých studentů</span>
</div>
<div class="col-xs-6 col-sm-3 col-sm-offset-2 placeholder">
    <div id="piechart2" style="width: 200px; height: 200px;"></div>
    <h4>Počet předmětů</h4>
    <span class="text-muted">Které byly vypsány</span>
</div>
</div>
<br /-->
<h2 class="sub-header">Problémové zápisy</h2>
<?php if (is_array(@$problems) && count($problems)):?>
<div class="table-responsive">
<table class="table table-striped">
    <thead>
    <tr>
        <th>ID zápisu</th>
        <th>Jméno</th>
        <th>Třída</th>
        <th>Počet problémů</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($problems as $entry):?>
    <tr>
        <td><a href="<?=$router->pathFor('subjects-admin-entries-edit', ['id' => $entry['id']])?>"><?=$entry['id']?></a></td>
        <td><?=$entry['user']->getAnyName()?></td>
        <td><?=$entry['user']->getLocalisedClass()?></td>
        <td><?=$entry['invalid']?></td>
    </tr>
    <?php endforeach;?>
    </tbody>
</table>
</div>
<?php else:?>
Žádné zápisy nemají problém
<?php endif;?>

<?php require __dir__."/sidebar/footer.phtml"?>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script>
google.charts.load('current', {'packages':['corechart']});
google.charts.setOnLoadCallback(drawCharts);

function drawCharts() {

    var data1 = google.visualization.arrayToDataTable([
        ['Stav', 'Počet studentů'],
        ['Bez zápisu', 25],
        ['Neschválený zápis', 2],
        ['Schválený zápis',  2],
        ['S uzavřeným předmětem', 2]
    ]);

    var data2 = google.visualization.arrayToDataTable([
        ['Stav', 'Počet studentů'],
        ['Otevřeno', 25],
        ['Uzavřeno', 2]
    ]);

    var options = {
        legend: {position: 'none'},
        chartArea: {top: 10, right: 10, bottom: 10, left: 10},
        colors: ["#36c", "#ff9900", "#109618", "#dc3912"]
    };

    var chart1 = new google.visualization.PieChart(document.getElementById('piechart1'));
    var chart2 = new google.visualization.PieChart(document.getElementById('piechart2'));

    chart1.draw(data1, options);
    chart2.draw(data2, Object.assign({}, options, {colors: ["#109618", "#dc3912"]}));
}
</script>