<div class="col-md-5">
    <h3><?=$lang->g('title', 'admin-manage', ['version' => $name])?></h3>
    <hr />
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong><?=$lang->g('new-title', 'admin-manage')?></strong>
    </div>
    <div class="panel-body">
    <p><?=$lang->g('new-format', 'admin-manage')?>
    <br />
    <pre>[region id];[author];[name];[genere id]</pre>
    </p>
    <form method="post" class="form-horizontal" enctype="multipart/form-data" action="<?=$router->pathFor('lists-admin-manage', ["id" => $version], ['mode' => 'upl'])?>">
        <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
        <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
        <input type="hidden" name="_METHOD" value="PUT" />
        <div class="col-md-12 form-group">
        <input type="file" name="book" />
        </div>
        <div class="col-md-6 form-group">
            <input type="submit" class="btn btn-default form-control" value="<?=$lang->g('new-submit', 'admin-manage')?>" />
        </div>
    </form>
    </div>
    </div>
    
    <div class="panel panel-default">
    <div class="panel-heading">
        <strong><?=$lang->g('books-title', 'admin-manage', ['count' => count($books)])?></strong>
        <div class="pull-right">
            <a href="#" id="toggle-list" data-toggle="collapse" data-target="#collapse-list"><?=$lang->g('books-expand', 'admin-manage')?></a>
        </div>
    </div>
    <div class="panel-body collapse" id="collapse-list">
    <?php if (is_array($books) && count($books)):?>
        <ul class='list-group'>
        <?php foreach($books as $book):?>
        <li class='list-group-item'>
            <span style="width: 75%;display: inline-block;"><?=$book['author'] == ""?"":$book['author'] . ": "?><b><?=$book['name']?></b></span>
        </li>
        <?php endforeach;?>
        </ul>
    <?php else:?>
        <span class='text-muted'><?=$lang->g('books-empty', 'admin-manage')?></span>
    <?php endif?>
    </div>
    </div>
</div>

<div class="col-md-5 col-md-offset-2">
    <h3><?=$lang->g('settings-title', 'admin-manage')?>
    <a href="<?=$router->pathFor('lists')?>" class="btn btn-default pull-right"><?=$lang->g('back', 'admin-manage')?></a>
    </h3>
    <hr />

    <div class="panel panel-default">
    <div class="panel-heading"><strong><?=$lang->g('settings-regions-title', 'admin-manage')?></strong></div>
    <div class="panel-body">
    <p><?=$lang->g('settings-regions-expected', 'admin-manage')?></p>
    <form method="post" class="form-horizontal" enctype="multipart/form-data" action="<?=$router->pathFor('lists-admin-manage', ["id" => $version], ['mode' => 'reg'])?>">
        <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
        <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
        <input type="hidden" name="_METHOD" value="PUT" />
        <?php foreach ($regionsCount as $regID):?>
            <div class="form-group">
                <label class="col-md-2 control-label" for="<?=$regID?>"><?=$lang->g('settings-regions-num', 'admin-manage', ['num' => $regID])?></label>
                <div class="col-md-5" style="padding: 0 5px">
                    <input class="form-control" type="text" name="reg[<?=$regID?>][name]" placeholder="<?=$lang->g('settings-regions-placeholder', 'admin-manage')?>"  value="<?=array_key_exists($regID, $regions)?$regions[$regID]['name']:''?>" required>
                </div>
                <div class="col-md-2" style="padding: 0 5px">
                    <input class="form-control" type="text" name="reg[<?=$regID?>][min]" placeholder="<?=$lang->g('settings-regions-min', 'admin-manage')?>" value="<?=array_key_exists($regID, $regions)?$regions[$regID]['min']:''?>">
                </div>
                <div class="col-md-2" style="padding: 0 5px">
                    <input class="form-control" type="text" name="reg[<?=$regID?>][max]" placeholder="<?=$lang->g('settings-regions-max', 'admin-manage')?>" value="<?=array_key_exists($regID, $regions)?$regions[$regID]['max']:''?>">
                </div>
            </div>
        <?php endforeach;?>
        <div class="col-md-4 form-group">
            <input type="submit" class="btn btn-default form-control" value="<?=$lang->g('settings-regions-submit', 'admin-manage')?>" />
        </div>
    </form>
    </div>
    </div>

    <div class="panel panel-default">
    <div class="panel-heading"><strong><?=$lang->g('settings-generes-title', 'admin-manage')?></strong></div>
    <div class="panel-body">
    <p><?=$lang->g('settings-generes-expected', 'admin-manage')?></p>
    <form method="post" class="form-horizontal" enctype="multipart/form-data" action="<?=$router->pathFor('lists-admin-manage', ["id" => $version], ['mode' => 'gen'])?>">
        <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
        <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
        <input type="hidden" name="_METHOD" value="PUT" />
        <?php foreach ($generesCount as $genID):?>
            <div class="form-group">
                <label class="col-md-2 control-label" for="<?=$genID?>"><?=$lang->g('settings-generes-num', 'admin-manage', ['num' => $genID])?></label>
                <div class="col-md-5" style="padding: 0 5px">
                    <input class="form-control" type="text" name="gen[<?=$genID?>][name]" placeholder="<?=$lang->g('settings-generes-placeholder', 'admin-manage')?>"  value="<?=array_key_exists($genID, $generes)?$generes[$genID]['name']:''?>" required>
                </div>
                <div class="col-md-2" style="padding: 0 5px">
                    <input class="form-control" type="text" name="gen[<?=$genID?>][min]" placeholder="<?=$lang->g('settings-generes-min', 'admin-manage')?>" value="<?=array_key_exists($genID, $generes)?$generes[$genID]['min']:''?>">
                </div>
                <div class="col-md-2" style="padding: 0 5px">
                    <input class="form-control" type="text" name="gen[<?=$genID?>][max]" placeholder="<?=$lang->g('settings-generes-max', 'admin-manage')?>" value="<?=array_key_exists($genID, $generes)?$generes[$genID]['max']:''?>">
                </div>
            </div>
        <?php endforeach;?>
        <div class="col-md-4 form-group">
            <input type="submit" class="btn btn-default form-control" value="<?=$lang->g('settings-generes-submit', 'admin-manage')?>" />
        </div>
    </form>
    </div>
    </div>
</div>

<script>
$('#toggle-list').click(function(){
    $(this).text(function(i,old){
        return old == "<?=$lang->g('books-expand', 'admin-manage')?>" ? "<?=$lang->g('books-collapse', 'admin-manage')?>" : "<?=$lang->g('books-expand', 'admin-manage')?>";
    });
});
</script>
