<div class="panel panel-default">
    <div class="panel-body">
        <p>Kánon zkontrolujte, odešlete a poté vytiskněte.</p>
        <?php if ($list['state'] != 0):?>
        <a class="btn btn-default" href="<?=$router->pathFor('lists')?>">Zpět</a>
        <div class="pull-right btn-group">
            <button class="btn btn-success disabled" data-toggle="tooltip" data-placement="top" title="Kánon již byl odeslán">Odeslat</button>
            <a href="<?=$router->pathFor('lists-generate', ['id' => $list['id']])?>" class="btn btn-primary" target="_blank">Tisk</a>
        </div>
        <?php else:?>
        <a class="btn btn-default" href="<?=$router->pathFor('lists-edit', ["id" => $list['id']])?>">Zpět</a>
        <div class="pull-right">
            <form method="post" action="<?=$router->pathFor('lists-validate', ["id" => $list['id']])?>">
                <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                <input type="hidden" name="_METHOD" value="PUT" />
                <div class="btn-group">
                    <button class="btn btn-success">Odeslat</button>
                    <button class="btn btn-primary disabled" data-toggle="tooltip" data-placement="top" title="Před tiskem kánon odešlete">Tisk</button>
                </div>
            </form>
        </div>
        <?php endif?>
    </div>
</div>
<h4>Knihy</h4>
<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th class="col-md-2">Autor</th>
            <th class="col-md-4">Dílo</th>
        </tr>
    </thead>
    <?php foreach($list['books'] as $book):?>
    <tr>
        <td><?=$book['author']?></td>
        <td><?=$book['name']?></td>
    </tr>
    <?php endforeach;?>
</table>
</div>