<div class="panel panel-default">
    <div class="panel-body">
        <p>Kánon zkontrolujte, odešlete a poté vytiskněte.</p>
        <?php if ($list['state'] != 0):?>
        <a class="btn btn-default" href="<?=$router->pathFor('lists')?>">Zpět</a>
        <div class="pull-right btn-group">
            <button class="btn btn-success disabled" data-toggle="tooltip" data-placement="top" title="Kánon již byl odeslán">Odeslat</button>
            <button class="btn btn-primary" onclick="window.print()">Tisk</button>
        </div>
        <?php else:?>
        <a class="btn btn-default" href="<?=$router->pathFor('lists-edit', ["id" => $list['id']])?>">Zpět</a>
        <div class="pull-right">
            <form method="post" action="<?=$router->pathFor('lists-validate', ["id" => $list['id']])?>">
                <input type="hidden" name="<?= $csrf['nameKey'] ?>" value="<?= $csrf['name'] ?>">
                <input type="hidden" name="<?= $csrf['valueKey'] ?>" value="<?= $csrf['value'] ?>">
                <input type="hidden" name="_METHOD" value="PUT" />
                <div class="btn-group">
                    <button class="btn btn-success">Odeslat</button>
                    <button class="btn btn-primary disabled" data-toggle="tooltip" data-placement="top" title="Před tiskem kánon odešlete">Tisk</button>
                </div>
            </form>
        </div>
        <?php endif?>
    </div>
</div>
<div class="print">
<div class="only-print">
<div class="footnote"><?=date("d. m. Y")?> – <b>SUPi</b> v<?=$config['version']?></div>
<img class="pull-right" src="data:image/png;base64,<?=$barcode?>">
<h3 style="margin-top: 4mm;">Kánon <?=$versionName?></h3>
<table>
    <tr>
        <td>Jméno:&nbsp;&nbsp;</td>
        <td><strong><?=implode(' ', $list['user']['name'])?></strong></td>
    </tr>
    <tr>
        <td>Třída: </td>
        <td><strong><?=$list['user']['class']?></strong></td>
    </tr>
</table>
<br />
</div>
<h4>Knihy</h4>
<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th class="col-md-2">Autor</th>
            <th class="col-md-4">Dílo</th>
        </tr>
    </thead>
    <?php foreach($list['books'] as $book):?>
    <tr>
        <td><?=$book['author']?></td>
        <td><?=$book['name']?></td>
    </tr>
    <?php endforeach;?>
</table>
<div class="only-print">
    <div class="signature"><h5>Podpis</h5></div>
    <div class="qr-code pull-right">
        <img src="<?=$qrcode?>"><br />
        <span style="text-align: center"><?=substr_replace($list['id'], '-', 3, 0)?></span>
    </div>
</div>
</div>
</div>